using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeaguePackets
{
    public enum GamePacketID : uint
    {
        Dummy                                    = 0x000, // DONE
        SPM_HierarchicalProfilerUpdate           = 0x001, // DONE
        S2C_DisplayLocalizedTutorialChatText     = 0x002, // DONE
        Barrack_SpawnUnit                        = 0x003, // DONE
        S2C_SwitchNexusesToOnIdleParticles       = 0x004, // DONE
        C2S_TutorialAudioEventFinished           = 0x005, // DONE
        S2C_SetCircularMovementRestriction       = 0x006, // DONE
        UpdateGoldRedirectTarget                 = 0x007, // DONE
        SynchSimTimeC2S                          = 0x008, // DONE
        RemoveItemReq                            = 0x009, // DONE
        ResumePacket                             = 0x00A, // DONE
        RemoveItemAns                            = 0x00B, // DONE
        Basic_Attack                             = 0x00C, // DONE
        S2C_ReplaceObjectiveText                 = 0x00D, // DONE
        S2C_CloseShop                            = 0x00E, // DONE
        S2C_Reconnect                            = 0x00F, // DONE
        UnitAddEXP                               = 0x010, // DONE
        S2C_EndSpawn                             = 0x011, // DONE
        SetFrequency                             = 0x012, // DONE
        S2C_BotAI                                = 0x013, // DONE
        C2S_QueryStatusReq                       = 0x014, // DONE
        NPC_UpgradeSpellAns                      = 0x015, // DONE
        C2S_Ping_Load_Info                       = 0x016, // DONE
        ChangeSlotSpellData                      = 0x017, // DONE
        NPC_MessageToClient_Broadcast            = 0x018, // DONE
        DisplayFloatingText                      = 0x019, // DONE
        Basic_Attack_Pos                         = 0x01A, // DONE
        NPC_ForceDead                            = 0x01B, // DONE
        NPC_BuffUpdateCount                      = 0x01C, // DONE
        C2S_WriteNavFlags_Acc                    = 0x01D, // DONE
        NPC_BuffReplaceGroup                     = 0x01E, // DONE
        NPC_SetAutocast                          = 0x01F, // DONE
        SwapItemReq                              = 0x020, // DONE
        NPC_Die_EventHistory                     = 0x021, // 
        UnitAddGold                              = 0x022, // DONE
        AddRegion                                = 0x023, // 
        S2C_MoveCameraToPoint                    = 0x024, // DONE
        S2C_LineMissileHitList                   = 0x025, // DONE
        S2C_MuteVolumeCategory                   = 0x026, // DONE
        ServerTick                               = 0x027, // DONE
        S2C_StopAnimation                        = 0x028, // DONE
        AvatarInfo_Server                        = 0x029, // DONE
        DampenerSwitchStates                     = 0x02A, // DONE
        World_SendCamera_Server_Acknologment     = 0x02B, // DONE
        S2C_ModifyDebugCircleRadius              = 0x02C, // DONE
        World_SendCamera_Server                  = 0x02D, // DONE
        HeroReincarnateAlive                     = 0x02E, // DONE
        NPC_BuffReplace                          = 0x02F, // DONE
        Pause                                    = 0x030, // DONE
        SetFadeOut_Pop                           = 0x031, // DONE
        RemoveRegion                             = 0x032, // DONE
        NPC_InstantStop_Attack                   = 0x033, // DONE
        OnLeaveLocalVisiblityClient              = 0x034, // DONE
        S2C_ShowObjectiveText                    = 0x035, // DONE
        CHAR_SpawnPet                            = 0x036, // DONE
        FX_Kill                                  = 0x037, // DONE
        NPC_UpgradeSpellReq                      = 0x038, // DONE
        UseObjectC2S                             = 0x039, // DONE
        MissileReplication                       = 0x03A, // 
        MovementDriverReplication                = 0x03B, // 
        S2C_HighlightHUDElement                  = 0x03C, // DONE
        SwapItemAns                              = 0x03D, // DONE
        NPC_LevelUp                              = 0x03E, // DONE
        S2C_MapPing                              = 0x03F, // DONE
        S2C_WriteNavFlags                        = 0x040, // 
        S2C_PlayEmote                            = 0x041, // DONE
        S2C_PlaySound                            = 0x042, // DONE
        S2C_PlayVOCommand                        = 0x043, // DONE
        S2C_OnEventWorld                         = 0x044, // 
        S2C_HeroStats                            = 0x045, // DONE
        C2S_UpdateGameOptions                    = 0x046, // DONE
        C2S_PlayEmote                            = 0x047, // DONE
        C2S_PlayVOCommand                        = 0x048, // DONE
        HeroReincarnate                          = 0x049, // DONE
        C2S_OnScoreBoardOpened                   = 0x04A, // 
        S2C_CreateHero                           = 0x04B, // DONE
        SPM_AddMemoryListener                    = 0x04C, // DONE
        SPM_HierarchicalMemoryUpdate             = 0x04D, // DONE
        S2C_ToggleUIHighlight                    = 0x04E, // DONE
        S2C_FaceDirection                        = 0x04F, // DONE
        OnLeaveVisiblityClient                   = 0x050, // DONE
        C2S_ClientReady                          = 0x051, // DONE
        SetItem                                  = 0x052, // DONE
        SynchVersionS2C                          = 0x053, // DONE
        S2C_HandleTipUpdate                      = 0x054, // DONE
        C2S_StatsUpdateReq                       = 0x055, // DONE
        C2S_MapPing                              = 0x056, // DONE
        S2C_RemoveDebugObject                    = 0x057, // DONE
        S2C_CreateUnitHighlight                  = 0x058, // DONE
        S2C_DestroyClientMissile                 = 0x059, // DONE
        S2C_SetSpellLevel                        = 0x05A, // DONE
        S2C_StartGame                            = 0x05B, // DONE
        C2S_OnShopOpened                         = 0x05C, // DONE
        NPC_Hero_Die                             = 0x05D, // DONE
        S2C_FadeOutMainSFX                       = 0x05E, // DONE
        Unused95                                 = 0x05F, // DONE
        WaypointGroup                            = 0x060, // CHECKME
        S2C_StartSpawn                           = 0x061, // DONE
        S2C_CreateNeutral                        = 0x062, // DONE
        WaypointGroupWithSpeed                   = 0x063, // CHECKME
        UnitApplyDamage                          = 0x064, // DONE
        ModifyShield                             = 0x065, // DONE
        S2C_PopCharacterData                     = 0x066, // DONE
        NPC_BuffAddGroup                         = 0x067, // DONE
        S2C_AI_TargetSelection                   = 0x068, // DONE
        AI_TargetS2C                             = 0x069, // DONE
        S2C_SetAnimStates                        = 0x06A, // DONE
        S2C_ChainMissileSync                     = 0x06B, // 
        C2S_OnTipEvent                           = 0x06C, // DONE
        S2C_ForceCreateMissile                   = 0x06D, // DONE
        BuyItemAns                               = 0x06E, // DONE
        S2C_SetSpellData                         = 0x06F, // DONE
        S2C_PauseAnimation                       = 0x070, // DONE
        NPC_IssueOrderReq                        = 0x071, // 
        S2C_CameraBehavior                       = 0x072, // DONE
        S2C_AnimatedBuildingSetCurrentSkin       = 0x073, // DONE
        Connected                                = 0x074, // DONE
        SyncSimTimeFinalS2C                      = 0x075, // DONE
        Waypoint_Acc                             = 0x076, // 
        AddPosPerceptionBubble                   = 0x077, // CHECKME
        S2C_LockCamera                           = 0x078, // DONE
        S2C_PlayVOAudioEvent                     = 0x079, // 
        AI_Command                               = 0x07A, // DONE
        NPC_BuffRemove2                          = 0x07B, // DONE
        SpawnMinionS2C                           = 0x07C, // 
        Unused125                                = 0x07D, // DONE
        S2C_ToggleFoW                            = 0x07E, // 
        S2C_ToolTipVars                          = 0x07F, // DONE
        Unused128                                = 0x080, // DONE
        World_LockCamera_Server                  = 0x081, // DONE
        BuyItemReq                               = 0x082, // DONE
        WaypointListHeroWithSpeed                = 0x083, // 
        S2C_SetInputLockFlag                     = 0x084, // DONE
        CHAR_SetCooldown                         = 0x085, // DONE
        CHAR_CancelTargetingReticle              = 0x086, // 
        FX_Create_Group                          = 0x087, // 
        S2C_QueryStatusAns                       = 0x088, // DONE
        Building_Die                             = 0x089, // DONE
        S2C_PreloadCharacterData                 = 0x08A, // 
        SPM_RemoveListener                       = 0x08B, // DONE
        S2C_HandleQuestUpdate                    = 0x08C, // 
        C2S_ClientFinished                       = 0x08D, // DONE
        SPM_RemoveMemoryListener                 = 0x08E, // DONE
        C2S_Exit                                 = 0x08F, // DONE
        S2C_ModifyDebugObjectColor               = 0x090, // DONE
        SPM_AddListener                          = 0x091, // DONE
        World_SendGameNumber                     = 0x092, // DONE
        SetPARState                              = 0x093, // 
        NPC_BuffRemoveGroup                      = 0x094, // DONE
        S2C_Ping_Load_Info                       = 0x095, // DONE
        S2C_ChangeCharacterVoice                 = 0x096, // DONE
        S2C_ChangeCharacterData                  = 0x097, // DONE
        S2C_Exit                                 = 0x098, // DONE
        SPM_RemoveBBProfileListener              = 0x099, // DONE
        NPC_CastSpellReq                         = 0x09A, // DONE
        S2C_ToggleInputLockFlag                  = 0x09B, // DONE
        C2S_SoftReconnect                        = 0x09C, // DONE
        S2C_CreateTurret                         = 0x09D, // DONE
        NPC_Die_Broadcast                        = 0x09E, // DONE
        UseItemAns                               = 0x09F, // DONE
        S2C_ShowAuxiliaryText                    = 0x0A0, // DONE
        PausePacket                              = 0x0A1, // DONE
        S2C_HideObjectiveText                    = 0x0A2, // DONE
        OnEvent                                  = 0x0A3, // 
        C2S_TeamSurrenderVote                    = 0x0A4, // DONE
        S2C_TeamSurrenderStatus                  = 0x0A5, // DONE
        SPM_AddBBProfileListener                 = 0x0A6, // DONE
        S2C_HideAuxiliaryText                    = 0x0A7, // DONE
        OnReplication_Acc                        = 0x0A8, // DONE
        S2C_SetGreyscaleEnabledWhenDead          = 0x0A9, // DONE
        S2C_AI_State                             = 0x0AA, // DONE
        S2C_SetFoWStatus                         = 0x0AB, // DONE
        ReloadScripts                            = 0x0AC, // DONE
        Cheat                                    = 0x0AD, // 
        OnEnterLocalVisiblityClient              = 0x0AE, // DONE
        SendSelectedObjID                        = 0x0AF, // DONE
        S2C_PlayAnimation                        = 0x0B0, // DONE
        S2C_RefreshAuxiliaryText                 = 0x0B1, // DONE
        SetFadeOut_Push                          = 0x0B2, // DONE
        S2C_OpenTutorialPopup                    = 0x0B3, // DONE
        S2C_RemoveUnitHighlight                  = 0x0B4, // DONE
        NPC_CastSpellAns                         = 0x0B5, // 
        SPM_HierarchicalBBProfileUpdate          = 0x0B6, // DONE
        NPC_BuffAdd2                             = 0x0B7, // DONE
        S2C_OpenAFKWarningMessage                = 0x0B8, // DONE
        WaypointList                             = 0x0B9, // 
        OnEnterVisiblityClient                   = 0x0BA, // 
        S2C_AddDebugObject                       = 0x0BB, // 
        S2C_DisableHUDForEndOfGame               = 0x0BC, // DONE
        SynchVersionC2S                          = 0x0BD, // DONE
        C2S_CharSelected                         = 0x0BE, // DONE
        NPC_BuffUpdateCountGroup                 = 0x0BF, // 
        AI_TargetHeroS2C                         = 0x0C0, // DONE
        SynchSimTimeS2C                          = 0x0C1, // DONE
        SyncMissionStartTimeS2C                  = 0x0C2, // DONE
        S2C_Neutral_Camp_Empty                   = 0x0C3, // 
        OnReplication                            = 0x0C4, // 
        S2C_EndOfGameEvent                       = 0x0C5, // DONE
        S2C_EndGame                              = 0x0C6, // DONE
        SPM_SamplingProfilerUpdate               = 0x0C7, // DONE
        S2C_PopAllCharacterData                  = 0x0C8, // DONE
        S2C_TeamSurrenderVote                    = 0x0C9, // DONE
        S2C_HandleUIHighlight                    = 0x0CA, // DONE
        S2C_FadeMinions                          = 0x0CB, // DONE
        C2S_OnTutorialPopupClosed                = 0x0CC, // DONE
        C2S_OnQuestEvent                         = 0x0CD, // DONE
        S2C_ShowHealthBar                        = 0x0CE, // 
        SpawnBotS2C                              = 0x0CF, // 
        SpawnLevelPropS2C                        = 0x0D0, // FIXME
        UpdateLevelPropS2C                       = 0x0D1, // 
        AttachFlexParticleS2C                    = 0x0D2, // DONE
        S2C_HandleCapturePointUpdate             = 0x0D3, // DONE
        S2C_HandleGameScore                      = 0x0D4, // DONE
        S2C_HandleRespawnPointUpdate             = 0x0D5, // DONE
        C2S_OnRespawnPointEvent                  = 0x0D6, // DONE
        S2C_UnitChangeTeam                       = 0x0D7, // DONE
        S2C_UnitSetMinimapIcon                   = 0x0D8, // DONE
        S2C_IncrementPlayerScore                 = 0x0D9, // DONE
        S2C_IncrementPlayerStat                  = 0x0DA, // DONE
        S2C_ColorRemapFX                         = 0x0DB, // DONE
        S2C_InteractiveMusicCommand              = 0x0DC, // 
        Unused221                                = 0x0DD, // DONE
        Unused222                                = 0x0DE, // DONE
        Unused223                                = 0x0DF, // DONE
        S2C_OnEnterTeamVisiblity                 = 0x0E0, // DONE
        S2C_OnLeaveTeamVisiblity                 = 0x0E1, // DONE
        S2C_FX_OnEnterTeamVisiblity              = 0x0E2, // DONE
        S2C_FX_OnLeaveTeamVisiblity              = 0x0E3, // DONE
        ReplayOnly_GoldEarned                    = 0x0E4, // DONE
        S2C_CloseClient                          = 0x0E5, // DONE
        C2S_SpellChargeUpdateReq                 = 0x0E6, // DONE
        S2C_ModifyDebugText                      = 0x0E7, // DONE
        S2C_SetDebugHidden                       = 0x0E8, // DONE
        S2C_ActivateMinionCamp                   = 0x0E9, // DONE
        C2S_SpectatorDataReq                     = 0x0EA, // 
        S2C_SpectatorMetaData                    = 0x0EB, // 
        S2C_SpectatorDataChunkInfo               = 0x0EC, // 
        S2C_SpectatorDataChunk                   = 0x0ED, // 
        S2C_ChangeMissileTarget                  = 0x0EE, // 
        S2C_MarkOrSweepForSoftReconnect          = 0x0EF, // DONE
        S2C_SetShopEnabled                       = 0x0F0, // DONE
        S2C_CreateFollowerObject                 = 0x0F1, // 
        S2C_ReattachFollowerObject               = 0x0F2, // 
        S2C_PlayContextualEmote                  = 0x0F3, // 
        C2S_PlayContextualEmote                  = 0x0F4, // 
        S2C_SetHoverIndicatorTarget              = 0x0F5, // DONE
        S2C_SetHoverIndicatorEnabled             = 0x0F6, // DONE
        S2C_SystemMessage                        = 0x0F7, // DONE
        S2C_ChangeEmitterGroup                   = 0x0F8, // DONE
        S2C_UpdateRestrictedChatCount            = 0x0F9, // DONE
        S2C_TeamBalanceVote                      = 0x0FA, // DONE
        C2S_TeamBalanceVote                      = 0x0FB, // DONE
        S2C_TeamBalanceStatus                    = 0x0FC, // DONE
        S2C_SetItemCharges                       = 0x0FD, // DONE
        ExtendedPacket                           = 0x0FE, // not an actual packet
        Batched                                  = 0x0FF, // not an actual packet
        SpawnMarkerS2C                           = 0x100, // DONE
        S2C_UnitSetAutoAttackGroundAllowed       = 0x101, // DONE
        S2C_UnitSetShowAutoAttackIndicator       = 0x102, // DONE
        S2C_AnimationUpdateTimeStep              = 0x103, // DONE
        S2C_UnitSetSpellPARCost                  = 0x104, // DONE
        S2C_UnitSetDrawPathMode                  = 0x105, // DONE
        C2S_UnitSendDrawPath                     = 0x106, // DONE
        S2C_AmmoUpdate                           = 0x107, // DONE
        S2C_UnitSetCursorReticle                 = 0x108, // DONE
        NPC_BuffUpdateNumCounter                 = 0x109, // DONE
        C2S_UndoItemReq                          = 0x10A, // DONE
        S2C_SetUndoEnabled                       = 0x10B, // DONE
        S2C_SetInventory_Broadcast               = 0x10C, // DONE
        S2C_ChangeMissileSpeed                   = 0x10D, // DONE
        S2C_SetCanSurrender                      = 0x10E, // DONE
        S2C_UnitSetLookAt                        = 0x10F, // DONE
        S2C_DestroyUnit                          = 0x110, // DONE
        S2C_UnitSetSpellLevelOverrides           = 0x111, // DONE
        S2C_UnitSetMaxLevelOverride              = 0x112, // DONE
        S2C_UnitSetPARType                       = 0x113, // DONE
        S2C_MoveMarker                           = 0x114, // DONE
        ReplayOnly_MultiKillCountUpdate          = 0x115, // DONE
        S2C_NeutralMinionTimerUpdate             = 0x116, // DONE
    }
}
